<?php
return [
   'adminEmail' => 'info@merosedu.uz',
   'supportEmail' => 'support@merosedu.uz',
   'senderEmail' => 'noreply@merosedu.uz',
   'senderName' => 'Meros Edu mailer',
   'telegramBotLink' => 'https://t.me/meros_info_bot',
   
   'coursePlatformUrl' => 'https://slc-campus.avallainmagnet.com/merosinternationalinstitute',
   'user.passwordResetTokenExpire' => 3600,
   'user.passwordMinLength' => 6,
   'user_status' => [
      10 => 'Active',
      9 => 'Inactive',
      0 => 'Deleted',
   ],
   'user_subscription_status' => [
      0 => 'Inactive',
      1 => 'Active',
   ],
   'status' => [
      0 => 'Inactive',
      1 => 'Active',
   ],
   'billing_status' => [
      'en' => [
         0 => 'Pending',
         1 => 'Success',
         2 => 'Failed',
         3 => 'Cancelled'
      ],
      'ru' => [
         0 => 'В процессе',
         1 => 'Успешно',
         2 => 'Ошибка',
         3 => 'Отменен'
      ],
      'uz'=>[
         0=>'Jarayonda',
         1=>'Muvaffaqiyatli',
         2=>'Xato',
         3=>'Bekor Qilingan',
      ]
   ],
   'billing_status_class' => [
      0 => 'badge bg-warning',
      1 => 'badge bg-success',
      2 => 'badge bg-danger',
      3 => 'badge bg-danger'
   ],
   'page_type' => [
      0 => 'B2B',
      1 => 'B2C',
   ],
   'faq_page_id' => [
      1 => 'faq-students',
      2 => 'faq-organisations',
   ],
   'medical_dictionary_categories' => [
      'ru' => [
         1  => 'Общая медицина',
         2  => 'Кардиология',
         3  => 'Неврология',
         4  => 'Пульмонология',
         5  => 'Гастроэнтерология',
         6  => 'Эндокринология',
         7  => 'Гематология',
         8  => 'Инфекционные заболевания',
         9  => 'Диагностика',
         10 => 'Фармакология',
         11 => 'Анатомия',
         12 => 'Неотложная помощь',
         13 => 'Нефрология и урология',
         14 => 'Онкология',
         15 => 'Иммунология и ревматология',
         16 => 'Акушерство и гинекология',
         17 => 'Хирургия',
         18 => 'Генетика',
         19 => 'Дерматология',
         20 => 'Офтальмология',
         21 => 'Оториноларингология (ЛОР)',
         22 => 'Психиатрия и психическое здоровье',
         23 => 'Педиатрия',
      ],
      
      'en' => [
         1  => 'General Medicine',
         2  => 'Cardiology',
         3  => 'Neurology',
         4  => 'Pulmonology',
         5  => 'Gastroenterology',
         6  => 'Endocrinology',
         7  => 'Hematology',
         8  => 'Infectious Diseases',
         9  => 'Diagnostics',
         10 => 'Pharmacology',
         11 => 'Anatomy',
         12 => 'Emergency Medicine',
         13 => 'Nephrology and Urology',
         14 => 'Oncology',
         15 => 'Immunology and Rheumatology',
         16 => 'Obstetrics and Gynecology',
         17 => 'Surgery',
         18 => 'Genetics',
         19 => 'Dermatology',
         20 => 'Ophthalmology',
         21 => 'Otorhinolaryngology (ENT)',
         22 => 'Psychiatry and Mental Health',
         23 => 'Pediatrics',
      ],
      
      'uz' => [
         1  => 'Umumiy tibbiyot',
         2  => 'Kardiologiya',
         3  => 'Nevrologiya',
         4  => 'Pulmonologiya',
         5  => 'Gastroenterologiya',
         6  => 'Endokrinologiya',
         7  => 'Gematologiya',
         8  => 'Yuqumli kasalliklar',
         9  => 'Diagnostika',
         10 => 'Farmakologiya',
         11 => 'Anatomiya',
         12 => 'Shoshilinch tibbiy yordam',
         13 => 'Nefrologiya va urologiya',
         14 => 'Onkologiya',
         15 => 'Immunologiya va revmatologiya',
         16 => 'Akusherlik va ginekologiya',
         17 => 'Jarrohlik',
         18 => 'Genetika',
         19 => 'Dermatologiya',
         20 => 'Oftalmologiya',
         21 => 'Otorinolaringologiya (LOR)',
         22 => 'Psixiatriya va ruhiy salomatlik',
         23 => 'Pediatriya',
      ],
   ],
   
   'medical_dictionary_types' => [
      'ru' => [
         1 => 'Заболевание / состояние',
         2 => 'Симптом / признак',
         3 => 'Анатомический термин',
         4 => 'Диагностика / показатель',
         5 => 'Процедура',
         6 => 'Фармакологический термин',
         7 => 'Общий медицинский термин',
      ],
      
      'en' => [
         1 => 'Disease / Condition',
         2 => 'Symptom / Sign',
         3 => 'Anatomical Term',
         4 => 'Diagnostic / Indicator',
         5 => 'Procedure',
         6 => 'Pharmacological Term',
         7 => 'General Medical Term',
      ],
      
      'uz' => [
         1 => 'Kasallik / holat',
         2 => 'Simptom / belgi',
         3 => 'Anatomik atama',
         4 => 'Diagnostika / ko‘rsatkich',
         5 => 'Protsedura',
         6 => 'Farmakologik atama',
         7 => 'Umumiy tibbiy atama',
      ],
   ],
];
